export interface SuriEntry {
  number: number;
  luck: '대길' | '길' | '중길' | '반흉' | '흉' | '대흉';
  name: string;
  description: string;
}

export const SURI_TABLE: SuriEntry[] = [
  { number: 1, luck: '대길', name: '만물창시운', description: '만물의 시작, 부귀영화를 누리는 수' },
  { number: 2, luck: '흉', name: '분리파멸운', description: '분리와 파멸의 암시, 고독한 수' },
  { number: 3, luck: '대길', name: '명예발달운', description: '지혜와 재능이 뛰어나 명성을 얻는 수' },
  { number: 4, luck: '흉', name: '부정불안운', description: '고난과 파괴가 따르는 불안한 수' },
  { number: 5, luck: '대길', name: '복록장수운', description: '건강과 장수, 복록이 겹치는 수' },
  { number: 6, luck: '대길', name: '천덕인복운', description: '하늘의 덕으로 만사형통하는 수' },
  { number: 7, luck: '길', name: '정진발달운', description: '강한 의지로 성공을 이루는 수' },
  { number: 8, luck: '길', name: '인내발달운', description: '인내와 노력으로 뜻을 이루는 수' },
  { number: 9, luck: '흉', name: '궁액빈곤운', description: '지혜는 있으나 실행력 부족한 수' },
  { number: 10, luck: '흉', name: '공허무상운', description: '허무와 좌절이 따르는 수' },
  { number: 11, luck: '대길', name: '온화축재운', description: '순탄하게 재물이 모이는 수' },
  { number: 12, luck: '흉', name: '박약중절운', description: '의지가 약하여 중도에 좌절하는 수' },
  { number: 13, luck: '대길', name: '지모총명운', description: '지혜와 재능으로 큰 뜻을 이루는 수' },
  { number: 14, luck: '흉', name: '이산고독운', description: '가족과 이별하고 고독한 수' },
  { number: 15, luck: '대길', name: '복수원만운', description: '복과 수명이 원만한 길수' },
  { number: 16, luck: '대길', name: '덕망고대운', description: '덕망이 높아 귀인의 도움을 받는 수' },
  { number: 17, luck: '길', name: '건달성취운', description: '강한 의지로 큰 성취를 이루는 수' },
  { number: 18, luck: '길', name: '발전유능운', description: '유능하여 발전하고 성공하는 수' },
  { number: 19, luck: '흉', name: '고난역경운', description: '장애물이 많아 고생하는 수' },
  { number: 20, luck: '흉', name: '허무단멸운', description: '공허하고 실속이 없는 수' },
  { number: 21, luck: '대길', name: '두령독립운', description: '지도자의 기질로 독립 성공하는 수' },
  { number: 22, luck: '흉', name: '중절좌사운', description: '중도에 좌절하기 쉬운 수' },
  { number: 23, luck: '대길', name: '왕성융창운', description: '왕성하게 번창하는 수' },
  { number: 24, luck: '대길', name: '입신양명운', description: '출세하여 이름을 떨치는 수' },
  { number: 25, luck: '길', name: '건실유덕운', description: '건실하고 덕이 있어 안정된 수' },
  { number: 26, luck: '반흉', name: '영웅운부족', description: '큰 뜻은 있으나 실현이 어려운 수' },
  { number: 27, luck: '반흉', name: '중도좌절운', description: '비난과 좌절이 따를 수 있는 수' },
  { number: 28, luck: '흉', name: '파란만장운', description: '풍파가 많고 고난이 따르는 수' },
  { number: 29, luck: '길', name: '지모성공운', description: '지략으로 성공을 이루는 수' },
  { number: 30, luck: '반흉', name: '길흉반반운', description: '길흉이 반반으로 불안정한 수' },
  { number: 31, luck: '대길', name: '지덕겸전운', description: '지혜와 덕을 겸비한 수' },
  { number: 32, luck: '대길', name: '요행횡재운', description: '행운이 따라 횡재하는 수' },
  { number: 33, luck: '대길', name: '융성발전운', description: '크게 번성하고 발전하는 수' },
  { number: 34, luck: '흉', name: '파멸재난운', description: '재난과 파멸이 따르는 수' },
  { number: 35, luck: '길', name: '온화평안운', description: '평화롭고 안정된 생활의 수' },
  { number: 36, luck: '반흉', name: '풍파만장운', description: '의협심은 있으나 풍파가 많은 수' },
  { number: 37, luck: '길', name: '인덕성공운', description: '사람의 덕으로 성공하는 수' },
  { number: 38, luck: '중길', name: '학예기능운', description: '학문과 예술에서 성공하는 수' },
  { number: 39, luck: '대길', name: '부귀영화운', description: '부귀와 영화가 함께하는 수' },
  { number: 40, luck: '반흉', name: '부침무상운', description: '부침이 심하여 안정되지 못하는 수' },
  { number: 41, luck: '대길', name: '만사대성운', description: '만사에 대성하는 수' },
  { number: 42, luck: '반흉', name: '고행수난운', description: '고생과 수난이 따르는 수' },
  { number: 43, luck: '흉', name: '산재실패운', description: '흩어지고 실패하기 쉬운 수' },
  { number: 44, luck: '흉', name: '침체몰락운', description: '침체하고 몰락하는 수' },
  { number: 45, luck: '대길', name: '순풍대성운', description: '순풍에 돛 달듯 크게 이루는 수' },
  { number: 46, luck: '반흉', name: '미운불성운', description: '뜻은 있으나 이루지 못하는 수' },
  { number: 47, luck: '대길', name: '출세개화운', description: '출세하여 꽃피우는 수' },
  { number: 48, luck: '대길', name: '지략유덕운', description: '지략과 덕이 겸비된 수' },
  { number: 49, luck: '반흉', name: '길흉반반운', description: '길흉이 뒤섞여 불안정한 수' },
  { number: 50, luck: '반흉', name: '성패부정운', description: '성공과 실패가 엇갈리는 수' },
  { number: 51, luck: '반흉', name: '성쇠교차운', description: '성함과 쇠함이 교차하는 수' },
  { number: 52, luck: '길', name: '선견지명운', description: '선견지명으로 성공하는 수' },
  { number: 53, luck: '반흉', name: '내허외실운', description: '겉은 좋으나 속이 허한 수' },
  { number: 54, luck: '흉', name: '고행빈곤운', description: '고생하고 가난한 수' },
  { number: 55, luck: '반흉', name: '미달불성운', description: '뜻에 미치지 못하는 수' },
  { number: 56, luck: '흉', name: '한탄부족운', description: '부족함에 한탄하는 수' },
  { number: 57, luck: '길', name: '노력성공운', description: '노력으로 성공을 이루는 수' },
  { number: 58, luck: '반흉', name: '선고후길운', description: '먼저 고생하고 나중에 좋아지는 수' },
  { number: 59, luck: '흉', name: '의지박약운', description: '의지가 약하여 이루지 못하는 수' },
  { number: 60, luck: '흉', name: '동요불안운', description: '흔들리고 불안한 수' },
  { number: 61, luck: '길', name: '영화부귀운', description: '영화와 부귀를 누리는 수' },
  { number: 62, luck: '흉', name: '쇠퇴고독운', description: '쇠퇴하고 고독한 수' },
  { number: 63, luck: '대길', name: '순성발전운', description: '순조롭게 발전하는 수' },
  { number: 64, luck: '흉', name: '침체부진운', description: '침체하고 부진한 수' },
  { number: 65, luck: '대길', name: '융창번영운', description: '융성하고 번영하는 수' },
  { number: 66, luck: '흉', name: '암야어둠운', description: '어두운 밤처럼 앞이 보이지 않는 수' },
  { number: 67, luck: '대길', name: '통달성취운', description: '뜻이 통하여 이루는 수' },
  { number: 68, luck: '대길', name: '명지확고운', description: '밝은 지혜로 확고히 성취하는 수' },
  { number: 69, luck: '흉', name: '동요불안운', description: '불안하고 동요하는 수' },
  { number: 70, luck: '흉', name: '공허적막운', description: '공허하고 적막한 수' },
  { number: 71, luck: '반흉', name: '반길반흉운', description: '길하면서도 흉한 수' },
  { number: 72, luck: '흉', name: '선길후흉운', description: '처음은 좋으나 나중이 나쁜 수' },
  { number: 73, luck: '중길', name: '평범무난운', description: '평범하나 무난한 수' },
  { number: 74, luck: '흉', name: '무능무력운', description: '능력이 부족하여 이루지 못하는 수' },
  { number: 75, luck: '반흉', name: '수양대기운', description: '수양하면 대기만성하는 수' },
  { number: 76, luck: '흉', name: '산란동요운', description: '산란하고 동요하는 수' },
  { number: 77, luck: '반흉', name: '길흉상반운', description: '길과 흉이 상반되는 수' },
  { number: 78, luck: '중길', name: '선고후안운', description: '먼저 고생하고 나중에 편안한 수' },
  { number: 79, luck: '흉', name: '고행무공운', description: '고생하여도 공이 없는 수' },
  { number: 80, luck: '반흉', name: '종결퇴은운', description: '끝을 맺고 물러나는 수' },
  { number: 81, luck: '대길', name: '환원시작운', description: '다시 시작하여 만물이 순환하는 수' },
];
